import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ViewGridIcon , SearchIcon , MicrophoneIcon, GlobeIcon} from '@heroicons/react/solid'
import Footer from '../component/Footer'
import { useRef } from 'react'
import {useRouter} from 'next/router'

export default function Home() {
  const searchRef = useRef(null)
  const router = useRouter()

  const handleSearch = (e) => {
    e.preventDefault();
    const term = searchRef.current.value;
    if(!term ) return;
    router.push(`/search?term=${term}`)

  }

  return (
    <div  className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex p-3 justify-between items-center w-full text-sm text-gray-500'>
        <div className='flex space-x-3 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        <div className='flex space-x-4 items-center'>
          <p className='link'>Mail</p>
          <p className='link'>Images</p>
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>
          <img loading='lazy' className='rounded-full h-10 cursor-pointer transition duration-150 transform hover:scale-110' src="https://express-images.franklymedia.com/3745/sites/5/2019/03/21220936/IMG_4249.jpg" alt='Profile Pic' ></img>
        </div>
      </header>
    
      <form className='flex flex-col items-center flex-1 mt-20 w-4/5'>
        <Image width={300} height={100} src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/272px-Google_2015_logo.svg.png?20160213081640'/>
        <div className=' sm:max-w-xl lg:max-w-2xl px-5 py-3 items-center flex focus-within:shadow-lg w-full mt-5 hover:shadow-lg rounded-full border border-gray-200  '>
          <SearchIcon className='h-5 mr-3 text-gray-500'/>
          <input type='text' ref={searchRef}  className='focus:outline-none focus:ring-0 flex-grow bg-transparent '/>
          <MicrophoneIcon className='h-5'  />
        </div>
        <div className='flex flex-col w-1/2 space-y-2 sm:space-y-0 justify-center mt-8 sm:flex-row sm:space-x-4 '>
          <button className='btn' type='submit' onClick={handleSearch} >Search Anything</button>
          <button className='btn'>Feeling Lucky</button>
        </div>
      </form>

      <Footer/>
    </div>

  )

}
